baseURL = "https://kplante.com"
title = "Kendra Plante"
theme = ["hugo-PaperMod","PaperMod-mods"]
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Kendra Plante"
description = "Personal Site"
keywords = [ "Portfolio" ]
author = "Kendra Plante"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "dark"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  disableFingerprinting = true
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Kendra Plante"
  subtitle = """
SIEM Engineer | Photographer | DarkSky Maryland
"""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/kp9001"

  [[params.socialIcons]]
  name = "bluesky"
  url = "https://bsky.app/profile/kplante.com"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@kplante"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/kendra-plante-1b4454249"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:kendra@kplante.com"

  [[params.socialIcons]]
  name = "signal"
  url = "https://signal.me/#eu/A7nbWqjkgJfvg53H2e-G1d-IF6greyBw-dlbKf-8OokOwvMUNmVCELEJBDV9ArvR"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 10

[[menu.main]]
identifier = "photography"
name = "Photography"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 30

[[menu.main]]
identifier = "papers"
name = "Papers"
url = "/papers"
weight = 40

[[menu.main]]
identifier = "PGP"
name = "PGP"
url = "https://mail-api.proton.me/pks/lookup?op=get&search=user.kendra@kplante.com"
weight = 50

[markup.highlight]
noClasses = false
lineNos = false
guessSyntax = true

[privacy]

  [privacy.disqus]
  disable = true
  
  [privacy.googleAnalytics]
  anonymizeIP = true
  disable = true
  respectDoNotTrack = true
  useSessionStorage = false
  
  [privacy.instagram]
  disable = true
  simple = false
  
  [privacy.twitter]
  disable = true
  enableDNT = true
  simple = false

  [privacy.x]
  disable = true
  enableDNT = true
  simple = false
  
  [privacy.vimeo]
  disable = true
  enableDNT = true
  simple = false
  
  [privacy.youtube]
  disable = true
  privacyEnhanced = true
